CREATE TABLE IMPIEGATO(
    NOME_BATT   	VARCHAR(15),
    INIZ_INT    	VARCHAR(1),
    COGNOME     	VARCHAR(15),
    SSN         	BIGINT,
    DATA_N      	VARCHAR(10),
    INDIRIZZO   	VARCHAR(255),
    SESSO       	VARCHAR(1),
    STIPENDIO   	BIGINT,
    SUPER_SSN   	BIGINT,
    N_D         	INTEGER,
    
    PRIMARY KEY (SSN)
);

CREATE TABLE DIPARTIMENTO (
    NOME_D 			VARCHAR(20),
    NUMERO_D 		INTEGER,
    SSN_DIR 		BIGINT,
    DATA_INIZIO_DIR VARCHAR(10),
    
    PRIMARY KEY (NUMERO_D)
);

CREATE TABLE SEDI_DIP (
	NUMERO_D 		INTEGER,
	SEDE_D 			VARCHAR(20),
	
    PRIMARY KEY (NUMERO_D, SEDE_D)
);

CREATE TABLE LAVORA_SU (
	SSN_I 			BIGINT,
	N_P 			INTEGER,
	ORE 			DECIMAL(10,2),

	PRIMARY KEY (SSN_I,N_P)
);

CREATE TABLE PROGETTO (
	NOME_P			VARCHAR(20),
	NUMERO_P		INTEGER,
	SEDE_P			VARCHAR(20),
	NUM_D			INTEGER,

	PRIMARY KEY (NUMERO_P)
);

create table PERSONA_A_CARICO (
	SSN_I 					BIGINT,
	NOME_PERSONA_A_CARICO 	VARCHAR(20),
	SESSO 					VARCHAR(1),
	DATA_N 					VARCHAR(10),
	PARENTELA 				VARCHAR(15),
    
	PRIMARY KEY (SSN_I,NOME_PERSONA_A_CARICO)
);

COMMIT;