---
vault:
  host: 127.0.0.1
  port: 8200
  scheme: http
  role-id: ${ROLE_ID}
  secret-id: ${SECRET_ID}

server:
  port: 18180
  servlet:
    contextPath: /iam

#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update



